### ISSUE TITLE
Dangerous tmp file write

### ISSUE THREAD

**Issue by igoyak** [YoungxHelsinki/automated-scripts#2]
https://github.com/YoungxHelsinki/automated-scripts/blob/3b8fd3813c73b96826b5693343e496797a13f9ee/Aalto_computer_status_checker/paniikki_jupyter_launcher.py#L183

Are you writing to this file in someone's home directory? What if that file already existed?

Consider something like this:
https://docs.python.org/3/library/tempfile.html

`>>> with tempfile.TemporaryDirectory() as tmpdirname:
...     print('created temporary directory', tmpdirname)`

**Comment by SuperShinyEyes** [comment]
Wow this is a great tip. Thanks!

**Comment by SuperShinyEyes** [comment]
Not writing any temp file at all. Load code via Popen().communicate()

Check https://github.com/YoungxHelsinki/automated-scripts/commit/97135732079d8600969d4ff02f6e339cadab8760
