### ISSUE TITLE
Unnecessary subprocess

### ISSUE THREAD

**Issue by igoyak** [YoungxHelsinki/automated-scripts#4]
https://github.com/YoungxHelsinki/automated-scripts/blob/3b8fd3813c73b96826b5693343e496797a13f9ee/Aalto_computer_status_checker/paniikki_jupyter_launcher.py#L237

You could simply use os.remove(). Or even better, using 'with tempfile.TemporaryDirectory()' the cleanup is automatic.

**Comment by SuperShinyEyes** [comment]
Agree.
